# docker-compose -f data-playground.yml up -d
version: "3.4"
services:

  adventure-works-db:
    image: stvansolano/adventure_works:latest
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"

  dotnet-sql-server:
    build:
      context: .
      dockerfile: samples/dotnet-sql-server/Dockerfile
    ports:
    - "80:80"
    links:
    - adventure-works-db
    depends_on:
    - adventure-works-db

  redis:
    image: redis:4.0.8-alpine
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: ingress
    volumes:
      - "~/data/${STACK_NAME}/redis:/data"